#!/bin/zsh

echo "Before proceeding!!! Ensure you have installed ohmyz.sh and have changed your shell to zshell"
echo "ctrl-C if you need to do this, otherwise press enter"
read

# Mac specific commands

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew install git
brew install curl
brew install cmake
brew install python
brew install python3
brew install vim

# Git commands (non OS specific)

git clone https://github.com/dan90210/dotfiles.git

rm ~/.vimrc
rm ~/.zshrc

ln -s -r ~/dotfiles/.vimrc ~/.vimrc

ln -s -r ~/dotfiles/.zshrcUbuntu ~/.zshrc

mkdir -p ~/.vim/autoload ~/.vim/bundle && \
    curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree

git clone https://github.com/tomasiser/vim-code-dark.git ~/.vim/bundle/vim-code-dark

git clone https://github.com/Chiel92/vim-autoformat.git ~/.vim/bundle/vim-autoformat

git clone https://github.com/tpope/vim-surround.git ~/.vim/bundle/vim-surround

git clone https://github.com/Valloric/YouCompleteMe.git ~/.vim/bundle/youcompleteme
echo "You must still finish installing YouCompleteMe!!!"
echo "Navigate to ~/.vim/bundle/youcompleteme"
echo "Then run ./install.py"
echo "Setup is complete!! (unless there were errors....)"
